# The URL the site will be built for
base_url = "https://goneri.lebouder.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "austere"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
title = "Gonéri's blog"

[search]
index_format = "fuse_javascript"

[extra]
# Put all your custom variables here
page_summary_on_paginator = true

# Social links
social_links = [
  { url = "https://bsky.app/profile/goneri.lebouder.net", name = "Bluesky" },
  { url = "https://www.linkedin.com/in/goneri/", name = "LinkedIn" },
  { url = "https://mastodon.social/@goneri", name = "Mastodon" }

]

menu_links = [
  { url = "$BASE_URL/", name = "Home" },
  { url = "$BASE_URL/posts/", name = "Posts" },
  { url = "$BASE_URL/about/", name = "About" },
  { url = "$BASE_URL/search/", name = "Search" },
]
